# 基于Node镜像来构建Vue项目
FROM node:14.6.0-alpine3.11

# 设置环境变量，临时配置npm镜像源为淘宝镜像
ENV NPM_CONFIG_REGISTRY=http://registry.npm.taobao.org

# 设置工作目录
WORKDIR /app

# 复制项目文件和nginx配置文件到工作目录
COPY frontend .
COPY hcp.conf .

WORKDIR /app/frontend

# 安装项目依赖
RUN npm install

# 安装依赖包
RUN npm i

# 构建Vue项目
RUN npm run build

# 使用Nginx基础镜像
FROM nginx:1.26.2-alpine3.20-perl

WORKDIR /app

# 将dist目录下的内容复制到容器内的/usr/share/nginx/html目录下
COPY --from=0 /app/dist /usr/share/nginx/html

# 将自定义的nginx配置文件复制到容器内的配置目录
COPY --from=0 /app/hcp.conf /etc/nginx/conf.d/default.conf