FROM alpine:latest AS builder

WORKDIR /app
RUN  sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories &&\
apk --no-cache add ca-certificates wget &&\
wget http://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.35-r1/glibc-2.35-r1.apk

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/glibc-2.35-r1.apk .
RUN  sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories &&\
wget -q -O /etc/apk/keys/sgerrand.rsa.pub http://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub &&\
apk add --no-cache glibc-2.35-r1.apk &&\
rm -rf * &&\
apk add --no-cache -U tzdata && \
cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

# 设置环境变量，确保应用使用 glibc
ENV LD_LIBRARY_PATH /usr/glibc-compat/lib

# 构建docker build ./ -t hcp-base:v1.0
