export const JSONConfig = {
  data() {
    return {
      JSONConfig: {
        cloudServer: {
          schema: "cloud_server",
          search: [
            "name",
            "cid",
            "private_ip",
            "public_ip",
            "server_image.name",
            "server_spec.name",
            "project_config.name",
            "account.alias",
          ],
          where:
            '{"project":{"cloudProjectAccountConfig":{"cloudProjectConfig":{"id":$id}}}}',
          properties: [
            {
              index: ["hash", "regexp"],
              list: false,
              name: "name",
              reference: null,
              title: "名称",
              type: "string",
              default: true,
              style: "lineFeedCopy",
              customStyle: [{ name: "cid" }],
            },
            {
              id: "0x32f88e",
              index: ["hash", "regexp"],
              list: false,
              name: "id",
              reference: null,
              title: "ID",
              type: "string",
              hide:true,
              hideIn:true
            },
            {
              id: "0x32f892",
              index: ["hash", "regexp"],
              list: false,
              name: "cid",
              reference: null,
              title: "云ID",
              type: "string",
              default: true,
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "status",
              reference: null,
              title: "状态",
              type: "string",
              default: true,
              enum: [
                { en: "running", zh: "运行中", style: "success" },
                { en: "pending", zh: "创建中", style: "warning" },
                { en: "starting", zh: "启动中", style: "warning" },
                { en: "stopping", zh: "停止中", style: "warning" },
                { en: "stopped", zh: "已停止", style: "warning" },
                { en: "unknown", zh: "其他", style: "info" },
              ],
            },
            {
              index: ["hash", "regexp"],
              list: true,
              name: "private_ip",
              reference: null,
              title: "内网IP",
              type: "string",
              hideIn: true,
              baseType:"网络信息"
            },
            {
              index: ["hash", "regexp"],
              list: true,
              name: "public_ip",
              reference: null,
              title: "公网IP",
              type: "string",
              hideIn: true,
              baseType:"网络信息"
            },
            {
              index: ["hash"],
              list: true,
              name: "",
              reference: null,
              title: "IP",
              type: "string",
              default: true,
              hide: true,
              customStyle: [
                { name: "private_ip", prefix: "(私)" },
                { name: "public_ip", prefix: "(公)" },
              ],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "zone.name",
              reference: null,
              title: "可用区",
              type: "string",
              schema: "cloud_zone",
              DataList: [],
              hideIn: true,
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "region.name",
              reference: null,
              title: "地域",
              type: "string",
              default: true,
              schema: "cloud_region",
              DataList: [],
              customStyle: [
                { name: "region.name" },
                { name: "zone.name", color: "#ccc" },
              ],
            },
            {
              list: false,
              name: "region.id",
              reference: null,
              title: "地域ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash", "regexp"],
              list: true,
              name: "subnet.name",
              reference: "cloud_subnet",
              title: "子网",
              type: "string",
              hideIn: true,
              baseType:"网络信息"
            },
            {
              index: null,
              list: true,
              name: "subnet.id",
              title: "子网ID",
              type: "object",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "vpc.name",
              reference: null,
              title: "专用网络",
              type: "string",
              default: false,
              customStyle: [
                {
                  name: "vpc.name",
                  link: "/compute/server/network/vpc",
                  linkId: "vpc.id",
                },
                {
                  name: "subnet.name",
                  link: "/compute/server/network/subnet",
                  linkId: "subnet.id",
                  prefix: "(子)",
                },
              ],
              baseType:"网络信息"
            },
            {
              index: ["hash"],
              list: false,
              name: "vpc.id",
              reference: null,
              title: "专用网络ID",
              type: "string",
              default: true,
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "server_image.name",
              reference: null,
              title: "镜像",
              type: "string",
              customStyle: [
                { name: "server_image.os_name" },
                {
                  name: "server_image.name",
                  link: "/compute/server/image/list",
                  linkId: "server_image.id",
                },
              ],
              baseType:"配置信息"
            },
            {
              index: ["hash"],
              list: false,
              name: "server_image.id",
              reference: null,
              title: "镜像ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: null,
              list: false,
              name: "server_image.os_name",
              reference: null,
              title: "系统版本",
              type: "string",
              hideIn: true,
              baseType:"配置信息"
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "server_spec.name",
              reference: null,
              title: "规格",
              type: "string",
              style: "serverType",
              customStyle: [
                {
                  cpuName: "server_spec.cpu",
                  memoryName: "server_spec.memory",
                  gpuName: "server_spec.gpu",
                  gpuModel: "server_spec.gpu_model",
                  diskSizeName: "",
                },
                { name: "server_spec.name" },
              ],
              baseType:"配置信息"
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "server_spec.cpu",
              reference: null,
              title: "CPU",
              type: "integer",
              unit: "核",
              hideIn: true,
              baseType:"配置信息"
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "server_spec.memory",
              reference: null,
              title: "内存",
              unit: "GB",
              type: "integer",
              hideIn: true,
              baseType:"配置信息"
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "server_spec.gpu",
              reference: null,
              title: "GPU",
              type: "integer",
              unit: "个",
              hideIn: true,
              baseType:"配置信息"
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "server_spec.gpu_model",
              reference: null,
              title: "GPU型号",
              type: "string",
              hideIn: true,
              baseType:"配置信息"
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "roject_config.id",
              reference: null,
              title: "项目ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "project_config.name",
              reference: null,
              title: "项目",
              type: "string",
              default: true,
              schema: "project_config",
              DataList: [],
              customStyle: [
                {
                  name: "project_config.name",
                  link: "/general/manage/project/list",
                  linkId: "project_config.id",
                },
                { name: "project.name", color: "#ccc", description: "(云)" },
              ],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "project.id",
              reference: null,
              title: "云项目ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "project.name",
              reference: null,
              title: "云项目",
              type: "string",
              default: true,
              hideIn: true,
              schema: "cloud_project",
              DataList: [],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "account.id",
              reference: null,
              title: "云账号ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "account.alias",
              reference: null,
              title: "云账号",
              type: "string",
              default: true,
              customStyle: [
                { name: "account.alias" },
                { name: "account.provider.name", urls: true },
              ],
              schema: "account",
              DataList: [],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "account.provider.name",
              reference: null,
              title: "厂商",
              type: "string",
              default: true,
              schema: "provider",
              customStyle: [
                { name: "account.provider.name", urls: true },
              ],
              DataList: [],
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "charge_type",
              reference: null,
              title: "计费方式",
              type: "string",
              enum: [
                { en: "prepaid", zh: "包年包月" },
                { en: "postpaid", zh: "按量付费" },
              ],
              customStyle: [
                { name: "chargeType" },
                { name: "expire_time", filterTime: true },
              ],
              baseType:"计费信息"
            },
            {
              index: ["hour"],
              list: false,
              name: "expire_time",
              title: "过期时间",
              type: "string",
              hideIn: true,
              baseType:"计费信息"
            },
            {
              list: false,
              name: "server_spec.cid",
              title: "规格码",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "renew_status",
              title: "续费状态",
              type: "string",
              enum: [
                { en: "auto", zh: "自动续费", style: "success" },
                { en: "manual", zh: "手动续费", style: "warning" },
                { en: "no", zh: "不续费", style: "danger" },
              ],
              hideIn: true,
              baseType:"计费信息"
            },
            {
              index: ["hour"],
              list: false,
              name: "create_time",
              title: "创建时间",
              type: "string",
              baseType:"计费信息"
            },
          ],
          tabs: [
            {
              title: "安全组",
              widget: "list",
              link: "/compute/server/network/securityGroup",
              schema: "cloud_security_group",
              where: '{"server":{"id":"$id"}}',
              search:[
                "cid",
                "name",
                "vpc.name"
              ],
              properties: [
                {
                  index: ["hash"],
                  list: false,
                  name: "id",
                  title: "ID",
                  type: "string",
                  hide:true,
                  hideIn:true
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "cid",
                  title: "云ID",
                  type: "string",
                },
                {
                  index: ["hash", "regexp"],
                  list: false,
                  name: "name",
                  title: "名称",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "status",
                  title: "状态",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "vpc.name",
                  title: "专用网络",
                  type: "string",
                  default: true,
                },
              ],
            },
          ],
        },
        Disk: {
          schema: "CloudDisk",
          where:
            '{"project":{"cloudProjectAccountConfig":{"cloudProjectConfig":{"id":$id}}}}',
          properties: [
            {
              index: ["hash", "regexp"],
              list: false,
              name: "name",
              reference: null,
              title: "名称",
              type: "string",
              default: true,
              style: "lineFeedCopy",
              customStyle: [{ name: "cid" }],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "id",
              reference: null,
              title: "ID",
              type: "string",
              hide:true,
              hideIn:true
            },
            {
              id: "0x32f892",
              index: ["hash"],
              list: false,
              name: "cid",
              reference: null,
              title: "云ID",
              type: "string",
              default: true,
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "status",
              reference: null,
              title: "状态",
              type: "string",
              enum: [
                { en: "in-use", zh: "已挂载", style: "success" },
                { en: "available", zh: "未挂载", style: "warning" },
                { en: "unknown", zh: "其他", style: "info" },
              ],
              default: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "usage",
              reference: null,
              title: "用途",
              type: "string",
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "device",
              reference: null,
              title: "设备",
              type: "string",
              hideIn: true,
            },
            {
              index: ["hash"],
              list: true,
              name: "instances.id",
              reference: "CloudServer",
              title: "云服务器ID",
              type: "string",
              hide: true,
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "instances.name",
              reference: "CloudServer",
              title: "云服务器",
              type: "string",
              default: true,
              customStyle: [
                {
                  name: "instances.name",
                  link: "/compute/server/instance/list",
                  linkId: "instances.id",
                },
                { name: "device", subName: "usage" },
              ],
            },
            {
              index: ["hash"],
              list: false,
              name: "size",
              reference: null,
              title: "硬盘大小",
              type: "integer",
              default: true,
              unit: "GB",
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "type",
              reference: null,
              title: "类型",
              type: "string",
              hideIn: true,
              enum: [
                { en: "HDD", zh: "普通硬盘" },
                { en: "EHDD", zh: "高效硬盘" },
                { en: "SSD", zh: "普通SSD" },
                { en: "ESSD", zh: "高效SSD" },
                { en: "unknown", zh: "其他" },
              ],
            },
            {
              index: ["hash"],
              list: false,
              name: "",
              reference: null,
              title: "规格",
              type: "string",
              hide: true,
              customStyle: [{ name: "size", unit: "(GB)" }, { name: "type" }],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "region.name",
              reference: null,
              title: "地域",
              type: "string",
              schema: "cloud_region",
              DataList: [],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "project.cloudProjectAccountConfig.cloudProjectConfig.id",
              reference: null,
              title: "项目ID",
              type: "string",
              hideIn: true,
              hide: true,
            },

            {
              index: ["hash"],
              list: false,
              name: "project.cloudProjectAccountConfig.cloudProjectConfig.name",
              reference: null,
              title: "项目",
              type: "string",
              default: true,
              customStyle: [
                {
                  name: "project.cloudProjectAccountConfig.cloudProjectConfig.name",
                  link: "/general/manage/project/list",
                  linkId:
                    "project.cloudProjectAccountConfig.cloudProjectConfig.id",
                },
                { name: "project.name", color: "#ccc", description: "(云)" },
              ],
            },
            {
              index: ["hash"],
              list: false,
              name: "project.name",
              reference: null,
              title: "云项目",
              type: "string",
              default: true,
              hideIn: true,
              schema: "cloud_project",
              DataList: [],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "account.id",
              reference: null,
              title: "云账号ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "account.id",
              reference: null,
              title: "云账号ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "account.alias",
              reference: null,
              title: "云账号",
              type: "string",
              customStyle: [
                { name: "account.alias" },
                { name: "account.provider.name", urls: true },
              ],
              default: true,
              schema: "account",
              DataList: [],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "account.provider.name",
              reference: null,
              title: "厂商",
              type: "string",
              default: true,
              schema: "provider",
              customStyle: [
                { name: "account.provider.name", urls: true },
              ],
              DataList: [],
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "device",
              reference: null,
              title: "挂载点",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "size",
              reference: null,
              title: "容量(GB)",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "instances.cid",
              reference: null,
              title: "云服务器云ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "instances.name",
              reference: null,
              title: "云服务器名称",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "instances.status",
              reference: null,
              title: "云服务器状态",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "chargeType",
              reference: null,
              title: "计费方式",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hour"],
              list: false,
              name: "create_time",
              title: "创建时间",
              type: "string",
            },
            {
              index: ["hash"],
              list: false,
              name: "expire_time",
              reference: null,
              title: "过期时间",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "renew_status",
              reference: null,
              title: "续费状态",
              type: "string",
              hideIn: true,
              hide: true,
            },
          ],
          tabs: [
            {
              title: "云服务器",
              widget: "list",
              link: "/compute/server/instance/list",
              schema: "CloudServer",
              where: '{"disks":{"id":"$id"}}',
              properties: [
                {
                  index: ["hash"],
                  list: false,
                  name: "id",
                  title: "ID",
                  type: "string",
                  hide:true,
                  hideIn:true
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "cid",
                  title: "云ID",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash", "regexp"],
                  list: false,
                  name: "name",
                  title: "名称",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "status",
                  title: "状态",
                  type: "string",
                  enum: [
                    { en: "running", zh: "运行中", style: "success" },
                    { en: "pending", zh: "创建中", style: "warning" },
                    { en: "starting", zh: "启动中", style: "warning" },
                    { en: "stopping", zh: "停止中", style: "warning" },
                    { en: "stopped", zh: "已停止", style: "warning" },
                    { en: "unknown", zh: "其他", style: "info" },
                  ],
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "zone.name",
                  title: "可用区",
                  type: "string",
                  default: true,
                },
              ],
            },
          ],
        },
        VPC: {
          schema: "cloud_vpc",
          projectNoget: true,
          where:
            '{"project":{"cloudProjectAccountConfig":{"cloudProjectConfig":{"id":$id}}}}',
          properties: [
            {
              index: ["hash", "regexp"],
              list: false,
              name: "name",
              reference: null,
              title: "名称",
              type: "string",
              default: true,
              style: "lineFeedCopy",
              customStyle: [{ name: "cid" }],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "id",
              reference: null,
              title: "ID",
              type: "string",
              hide:true,
              hideIn:true
            },
            {
              id: "0x32f892",
              index: ["hash"],
              list: false,
              name: "cid",
              reference: null,
              title: "云ID",
              type: "string",
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "status",
              reference: null,
              title: "状态",
              type: "string",
              default: true,
              enum: [
                { en: "available", zh: "可用", style: "success" },
                { en: "unavailable", zh: "不可用", style: "danger" },
                { en: "unknown", zh: "其他", style: "info" },
              ],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "region.name",
              reference: null,
              title: "地域",
              type: "string",
              default: true,
              schema: "cloud_region",
              DataList: [],
            },
            {
              id: "0x32f88e",
              list: false,
              name: "region.id",
              reference: null,
              title: "地域ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "project_config.id",
              reference: null,
              title: "项目ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "project_config.name",
              reference: null,
              title: "项目",
              type: "string",
              default: true,
              schema: "project_config",
              DataList: [],
              customStyle: [
                {
                  name: "project_config.name",
                  link: "/general/manage/project/list",
                  linkId:
                    "project_config.id",
                },
                { name: "project.name", color: "#ccc", description: "(云)" },
              ],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "project.id",
              reference: null,
              title: "云项目ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "project.name",
              reference: null,
              title: "云项目",
              type: "string",
              default: true,
              hideIn: true,
              schema: "cloud_project",
              DataList: [],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "account.id",
              reference: null,
              title: "云账号ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "account.alias",
              title: "云账号",
              type: "string",
              default: true,
              customStyle: [
                { name: "account.alias" },
                { name: "account.provider.name", urls: true },
              ],
              schema: "account",
              DataList: [],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "account.provider.name",
              reference: null,
              title: "厂商",
              type: "string",
              default: true,
              schema: "provider",
              customStyle: [
                { name: "account.provider.name", urls: true },
              ],
              DataList: [],
              hideIn: true,
            },
          ],
          tabs: [
            {
              title: "子网",
              widget: "list",
              link: "/compute/server/network/subnet",
              schema: "cloud_subnet",
              where: '{"vpc":{"id":"$id"}}',
              properties: [
                {
                  index: ["hash"],
                  list: false,
                  name: "id",
                  title: "ID",
                  type: "string",
                  hide:true,
                  hideIn:true
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "cid",
                  title: "云ID",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash", "regexp"],
                  list: false,
                  name: "name",
                  title: "名称",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "status",
                  title: "状态",
                  type: "string",
                  enum: [
                    { en: "available", zh: "可用", style: "success" },
                    { en: "unavailable", zh: "不可用", style: "danger" },
                  ],
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "zone.name",
                  title: "可用区",
                  type: "string",
                  default: true,
                },
              ],
            },
            {
              title: "安全组",
              widget: "list",
              link: "/compute/server/network/securityGroup",
              schema: "cloud_security_group",
              where: '{"vpc":{"id":"$id"}}',
              properties: [
                {
                  index: ["hash"],
                  list: false,
                  name: "id",
                  title: "ID",
                  type: "string",
                  hide:true,
                  hideIn:true
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "cid",
                  title: "云ID",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash", "regexp"],
                  list: false,
                  name: "name",
                  title: "名称",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "status",
                  title: "状态",
                  type: "string",
                  default: true,
                },
              ],
            }
          ],
        },
        subNet: {
          schema: "cloud_subnet",
          projectNoget: true,
          where:
            '{"project":{"cloudProjectAccountConfig":{"cloudProjectConfig":{"id":$id}}}}',
          properties: [
            {
              index: ["hash", "regexp"],
              list: false,
              name: "name",
              reference: null,
              title: "名称",
              type: "string",
              default: true,
              style: "lineFeedCopy",
              customStyle: [{ name: "cid" }],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "id",
              reference: null,
              title: "ID",
              type: "string",
              hide:true,
              hideIn:true
            },
            {
              id: "0x32f892",
              index: ["hash"],
              list: false,
              name: "cid",
              reference: null,
              title: "云ID",
              type: "string",
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "status",
              reference: null,
              title: "状态",
              type: "string",
              default: true,
              enum: [
                { en: "available", zh: "可用", style: "success" },
                { en: "unavailable", zh: "不可用", style: "danger" },
                { en: "unknown", zh: "其他", style: "info" },
              ],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "vpc.region.name",
              reference: null,
              title: "地域",
              type: "string",
              default: true,
              schema: "cloud_region",
              DataList: [],
              customStyle: [
                { name: "vpc.region.name" },
                { name: "zone.name", color: "#ccc" },
              ],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "zone.name",
              reference: null,
              title: "可用区",
              type: "string",
              default: true,
              schema: "cloud_zone",
              DataList: [],
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "vpc.name",
              reference: null,
              default: true,
              title: "专用网络",
              type: "string",
              customStyle: [
                {
                  name: "vpc.name",
                  link: "/compute/server/network/vpc",
                  linkId: "vpc.id",
                },
              ],
              baseType:"配置信息"
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "project_config.id",
              reference: null,
              title: "项目ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "project_config.name",
              reference: null,
              title: "项目",
              type: "string",
              default: true,
              schema: "project_config",
              DataList: [],
              customStyle: [
                {
                  name: "project_config.name",
                  link: "/general/manage/project/list",
                  linkId:
                    "project_config.id",
                },
                { name: "project.name", color: "#ccc", description: "(云)" },
              ],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "project.id",
              reference: null,
              title: "云项目ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "project.name",
              reference: null,
              title: "云项目",
              type: "string",
              default: true,
              hideIn: true,
              schema: "cloud_project",
              DataList: [],
            },
            {
              index: ["hash"],
              list: false,
              name: "vpc.id",
              reference: null,
              title: "专用网络ID",
              type: "string",
              default: true,
              hideIn: true,
              hide: true,
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "account.id",
              reference: null,
              title: "云账号ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "account.alias",
              reference: null,
              title: "云账号",
              type: "string",
              default: true,
              customStyle: [
                { name: "account.alias" },
                { name: "account.provider.name", urls: true },
              ],
              schema: "account",
              DataList: [],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "account.provider.name",
              reference: null,
              title: "厂商",
              type: "string",
              default: true,
              schema: "provider",
              customStyle: [
                { name: "account.provider.name", urls: true },
              ],
              DataList: [],
              hideIn: true,
            },
          ],
        },
        CloudProvider: {
          schema: "provider",
          noStatus: true,
          properties: [
            {
              index: ["hash"],
              list: false,
              name: "id",
              title: "ID",
              type: "string",
              hide:true,
              hideIn:true
            },
            {
              index: ["regexp", "hash"],
              list: false,
              name: "name",
              title: "名称",
              type: "string",
              default: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "alias",
              title: "编号",
              type: "string",
              default: true,
            },
            {
              list: false,
              name: "account_number",
              title: "账号数量",
              type: "string",
              default: true,
              hide: true,
            },
            {
              list: false,
              name: "pre_sale_contacts",
              title: "售前联系人",
              type: "string",
              default: true,
              "baseType": "联系方式"
            },
            {
              list: false,
              name: "after_sale_contacts",
              title: "售后联系人",
              type: "string",
              default: true,
              "baseType": "联系方式"
            },
            {
              list: false,
              name: "business_contacts",
              title: "商务联系人",
              type: "string",
              default: true,
              "baseType": "联系方式"
            },
          ],
          tabs: [
            {
              title: "云账号",
              schema: "account",
              link: "/general/manage/account/list",
              widget: "list",
              where: '{"provider":{"id":"$id"}}',
              properties: [
                {
                  index: ["hash"],
                  list: false,
                  name: "id",
                  title: "ID",
                  type: "string",
                  hide:true,
                  hideIn:true
                },
                {
                  index: ["regexp", "hash"],
                  list: false,
                  name: "name",
                  title: "云名称",
                  type: "string",
                  default: true,
                },
                {
                  index: ["regexp", "hash"],
                  list: false,
                  name: "cid",
                  title: "云ID",
                  type: "string",
                  default: true,
                },
                {
                  index: ["regexp", "hash"],
                  list: false,
                  name: "alias",
                  title: "别名",
                  type: "string",
                  default: true,
                },
              ],
            },
          ],
        },
        Useraccount: {
          schema: "account",
          projectNoget: true,
          properties: [
            {
              index: ["hash"],
              list: false,
              name: "id",
              title: "ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["regexp", "hash"],
              list: false,
              name: "name",
              title: "名称",
              type: "string",
              default: true,
              style: "lineFeedCopy",
              customStyle: [{ name: "cid" }],
            },
            {
              index: ["regexp", "hash"],
              list: false,
              name: "alias",
              title: "别名",
              type: "string",
              default: true,
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "provider.name",
              title: "厂商",
              type: "string",
              default: true,
              schema: "provider",
              DataList: [],
              customStyle: [{ name: "provider.name", urls: true }],
            },
            {
              index: ["hash"],
              list: false,
              name: "cid",
              title: "云ID",
              type: "string",
              default: true,
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "subject",
              title: "主体",
              type: "string",
              default: true,
            },
            {
              index: ["regexp", "hash"],
              list: false,
              name: "sync_secret_id",
              title: "同步账号",
              type: "string",
              default: true,
            },
            {
              index: ["regexp", "hash"],
              list: false,
              name: "operate_secret_id",
              title: "操作账号",
              type: "string",
              default: true,
            },
            
            {
              index: ["hash", "regexp"],
              list: false,
              name: "provider.id",
              reference: "provider",
              title: "厂商id",
              type: "string",
              hide: true,
              hideIn: true,
              DataList: [],
            },
            {
              list: false,
              name: "email",
              title: "邮箱",
              type: "string",
            },
            {
              list: false,
              name: "key_pair_id",
              title: "密钥对ID",
              type: "string",
            },
            {
              list: false,
              name: "key_pair_name",
              title: "密钥对名称",
              type: "string",
            },
            {
              list: false,
              name: "phone",
              title: "联系电话",
              type: "string",
            },
            {
              index: ["hash"],
              list: false,
              name: "description",
              title: "备注",
              type: "string",
              default: true,
            },
          ],
          tabs: [
            {
              title: "可用地域",
              widget: "list",
              schema: "cloud_region",
              where: '{"account":{"id":"$id"}}',
              properties: [
                {
                  index: ["hash"],
                  list: false,
                  name: "id",
                  title: "ID",
                  type: "string",
                  hide:true,
                  hideIn:true
                },
                {
                  index: ["hash", "regex"],
                  list: false,
                  name: "cid",
                  title: "云ID",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash", "regexp"],
                  list: false,
                  name: "name",
                  title: "名称",
                  type: "string",
                  default: true,
                },
              ],
            },
          ],
        },
        securityGrouplist: {
          schema: "cloud_security_group",
          properties: [
            {
              index: ["hash"],
              list: false,
              name: "id",
              title: "ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["regexp", "hash"],
              list: false,
              name: "name",
              title: "名称",
              type: "string",
              default: true,
              style: "lineFeedCopy",
              customStyle: [{ name: "cid" }],
            },
            {
              index: ["hash"],
              list: false,
              name: "cid",
              title: "云ID",
              type: "string",
              default: true,
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "status",
              title: "状态",
              type: "string",
              enum: [
                { en: "available", zh: "可用", style: "success" },
                { en: "unknown", zh: "其他", style: "danger" },
                { en: "unknown", zh: "其他", style: "info" },
              ],
              default: false,
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "region.name",
              title: "地域",
              type: "string",
              default: true,
              schema: "cloud_region",
              DataList: [],
            },
            {
              index: ["hash"],
              list: false,
              name: "vpc.id",
              reference: null,
              title: "专用网络ID",
              type: "string",
              default: true,
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "vpc.name",
              title: "专用网络",
              type: "string",
              default: true,
              customStyle: [
                {
                  name: "vpc.name",
                  link: "/compute/server/network/vpc",
                  linkId: "vpc.id",
                },
              ],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "project_config.id",
              reference: null,
              title: "项目ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "project_config.name",
              reference: null,
              title: "项目",
              type: "string",
              default: true,
              schema: "project_config",
              DataList: [],
              customStyle: [
                {
                  name: "project_config.name",
                  link: "/general/manage/project/list",
                  linkId:
                    "project_config.id",
                },
                { name: "project.name", color: "#ccc", description: "(云)" },
              ],
            },
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "project.id",
              reference: null,
              title: "云项目ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "project.name",
              title: "云项目",
              type: "string",
              default: true,
              hideIn: true,
              schema: "cloud_project",
              DataList: [],
            },
            {
              index: ["hash"],
              list: false,
              name: "account.id",
              title: "云账号ID",
              type: "string",
              hideIn: true,
              hide: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "account.alias",
              title: "云账号",
              type: "string",
              default: true,
              customStyle: [
                { name: "account.alias" },
                { name: "account.provider.name", urls: true },
              ],
              schema: "account",
              DataList: [],
            },
            {
              index: ["hash", "regexp"],
              list: false,
              name: "account.provider.name",
              title: "厂商",
              type: "string",
              default: true,
              customStyle: [
                { name: "account.provider.name", urls: true },
              ],
              DataList: [],
              hideIn: true,
              schema: "provider",
            },
            {
              index: ["hour"],
              list: false,
              name: "create_time",
              title: "创建时间",
              type: "string",
            },
          ]
        },
        serverImage: {
          schema: "cloud_server_image",
          projectNoget: true,
          properties: [
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "id",
              reference: null,
              title: "ID",
              type: "string",
              default: true,
            },
            {
              index: ["regexp", "hash"],
              list: false,
              name: "name",
              reference: null,
              title: "名称",
              type: "string",
              default: true,
              style: "lineFeedCopy",
              customStyle: [{ name: "cid" }],
            },
            {
              id: "0x32f892",
              index: ["hash"],
              list: false,
              name: "cid",
              reference: null,
              title: "cid",
              type: "string",
              default: true,
              hideIn: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "os_name",
              reference: null,
              title: "系统版本",
              type: "string",
              default: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "type",
              reference: null,
              title: "类型",
              type: "string",
              default: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "status",
              reference: null,
              title: "状态",
              type: "string",
              default: true,
              enum: [
                { en: "available", zh: "可用", style: "success" },
                { en: "unavailable", zh: "不可用", style: "danger" },
                { en: "unknown", zh: "其他", style: "info" },
              ],
            },
            {
              index: ["hash"],
              name: "region.name",
              schema: "cloud_region",
              title: "区域",
              type: "string",
            },
            {
              index: ["hash"],
              name: "account.alias",
              title: "账号",
              type: "string",
            },
            {
              index: ["hash"],
              list: true,
              name: "account.provider.name",
              title: "厂商",
              type: "string",
              default: true,
              schema: "provider",
              customStyle: [
                { name: "account.provider.name", urls: true },
              ],
              DataList: [],
            },
          ],
        },
        projectManage: {
          projectNoget: true,
          schema: "project_config",
          where: '{"id":$id}',
          properties: [
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "id",
              reference: null,
              title: "ID",
              type: "string",
            },
            {
              index: ["regexp", "hash"],
              list: null,
              name: "name",
              reference: null,
              title: "名称",
              type: "string",
              default: true,
              style: "lineFeedCopy",
            },
            {
              index: ["regexp", "hash"],
              list: false,
              name: "alias",
              reference: null,
              title: "别名",
              type: "string",
              default: true,
            },
            {
              index: ["regexp", "hash"],
              list:true,
              name: "op_leader.name",
              schema: "user",
              DataList:[],
              title: "项目运维负责人",
              type: "string",
              default: true,
              "baseType": "成员信息"
            },
            {
              index: ["regexp", "hash"],
              list:true,
              name: "rd_leader.name",
              schema: "user",
              DataList:[],
              title: "项目研发负责人",
              type: "string",
              default: true,
              "baseType": "成员信息"
            },
            {
              index: ["regexp", "hash"],
              list:true,
              name: "op_member.name",
              schema: "user",
              DataList:[],
              title: "项目运维成员",
              type: "string",
              default: true,
              "baseType": "成员信息"
            },
            {
              index: ["regexp", "hash"],
              list:true,
              name: "rd_member.name",
              schema: "user",
              DataList:[],
              title: "项目研发成员",
              type: "string",
              default: true,
              "baseType": "成员信息"
            },
            {
              index: ["regexp", "hash"],
              list: null,
              name: "description",
              reference: null,
              title: "描述",
              type: "string"
            }
          ],
          tabs: [
            {
              title: "账号配置",
              widget: "list",
              link: "/general/manage/project/account",
              schema: "project_account_config",
              where: '{"cloudProjectConfig":{"id":"$id"}}',
              search:["project_config.name"],
              properties: [
                {
                  index: ["hash"],
                  list: false,
                  name: "id",
                  title: "ID",
                  type: "string",
                },
                {
                  index: ["hash", "regexp"],
                  list: false,
                  name: "project_config.name",
                  title: "名称",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "account.alias",
                  title: "云账号",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "account.provider.name",
                  title: "厂商",
                  type: "string",
                  default: true,
                  customStyle: [{ name: "account.provider.name", urls: true }],
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "project.name",
                  title: "云项目",
                  type: "string",
                  default: true,
                  schema: "cloud_project",
                  DataList: [],
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "project.id",
                  title: "云项目id",
                  type: "string",
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "cloud_label.value",
                  title: "云标签",
                  type: "string",
                  default: true,
                },
                {
                  index: ["hash"],
                  list: false,
                  name: "cloud_label.id",
                  title: "云标签id",
                  type: "string",
                },
              ],
            },
          ],
        },
        accountManage: {
          projectNoget: true,
          schema: "project_account_config",
          where: '{"cloudProjectConfig":{"id":$id}}',
          search:[
            "project_config.name",
            "project.name",
          ],
          name:"project_config.name",
          properties: [
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "id",
              reference: null,
              title: "ID",
              type: "string",
              hide:true,
              hideIn:true
            },
            {
              index: ["regexp", "hash"],
              list: null,
              name: "project_config.name",
              reference: null,
              title: "名称",
              type: "string",
              default: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "account.alias",
              reference: null,
              title: "云账号",
              type: "string",
              default: true,
              schema: "account",
              DataList: [],
            },
            {
              index: ["hash"],
              list: false,
              name: "account.provider.name",
              reference: null,
              title: "厂商",
              type: "string",
              default: true,
              customStyle: [{ name: "account.provider.name", urls: true }],
              schema: "provider",
              DataList: [],
            },
            {
              index: ["hash"],
              list: false,
              name: "project.name",
              reference: null,
              title: "项目",
              type: "string",
              default: true,
              schema: "cloud_project",
              DataList: [],
            },
            {
              index: ["hash"],
              list: false,
              name: "project_config.name",
              reference: null,
              title: "云项目",
              type: "string",
              default: true,
              schema: "project_config",
              DataList: [],
            },
          ],
        },
        User: {
          projectNoget: true,
          schema: "user",
          properties: [
            {
              id: "0x32f88e",
              index: ["hash"],
              list: false,
              name: "id",
              reference: null,
              title: "ID",
              type: "string",
              hide:true,
              hideIn:true
            },
            {
              index: ["regexp", "hash"],
              list: null,
              name: "name",
              reference: null,
              title: "名称",
              type: "string",
              default: true,
              style: "lineFeedCopy",
            },
            {
              index: ["regexp", "hash"],
              list: false,
              name: "role",
              reference: null,
              title: "角色",
              type: "string",
              default: true,
              enum: [
                { en: 1, zh: "超级管理员" },
                { en: 2, zh: "管理员" },
                { en: 3, zh: "用户" },
              ],
            },
            {
              index: ["hash"],
              list: false,
              name: "create_time",
              reference: null,
              title: "创建时间",
              type: "string",
              default: true,
            },
            {
              index: ["hash"],
              list: false,
              name: "update_time",
              reference: null,
              title: "更新时间",
              type: "string",
              default: true,
            },
          ],
        },
      },
    };
  },
};
